#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    n = len(arr)
    positives = sum(1 for i in arr if i > 0)
    negatives = sum(1 for i in arr if i < 0)
    zeros = sum(1 for i in arr if i == 0)
    print("{:.6f}".format(positives / n))
    print("{:.6f}".format(negatives / n))
    print("{:.6f}".format(zeros / n))

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
